// Generated by CoffeeScript 2.5.1
import {
  mcron
} from './index.js';

(() => {
  return mcron(() => {
    return console.log(new Date().toLocaleString());
  }, 2);
})();

//# sourceMappingURL=index_test.js.map
